In [1]:
import pandas as pd

In [2]:
def make_numeric(file_name):
  """
  Encodes all responses exlcuding "NO SMS" as 1, otherwise 0

  Input: data_file: file name of non-encoded data file
  """
  data = pd.read_csv(file_name)
  response = (data[[i for i in data.columns if 'Day' in i]] != "NO SMS").astype(int)
  meta_data = data[[i for i in data.columns if 'Day' not in i]]
  res = pd.concat([meta_data, response], axis = 1)
  return res

In [7]:
file_name = "data/client_daily_reponse_details_clients.csv"
res = make_numeric(file_name)
res

,Client_ID,Enrolment Date,Facility,Day 1,Day 2,Day 3,Day 4,Day 5,Day 6,Day 7,Day 8,Day 9,Day 10,Day 11,Day 12,Day 13
0,1,21-Aug-23,1,1,1,1,1,1,1,1,1,1,1,1,0,1
1,2,30-Sep-23,2,1,0,0,0,1,0,0,0,0,0,0,0,0
2,3,3-Oct-23,3,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,7-Sep-23,4,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,17-Aug-23,1,1,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,2153,28-Sep-23,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2153,2154,28-Sep-23,2,0,0,0,0,0,0,0,0,0,0,0,0,0
2154,2155,15-Sep-23,3,1,1,1,1,1,1,1,1,1,1,1,1,1
2155,2156,29-Sep-23,4,0,0,1,1,0,0,1,0,0,0,0,0,0
2156,2157,26-Sep-23,1,1,1,1,1,1,1,1,1,1,1,1,0,1